#!/bin/zsh

SEP=`echo ""`
if git_status=$(cd $1 && git status 2>/dev/null ); then
  git_branch="$(echo $git_status| awk 'NR==1 {print $3}')"
  case $git_status in
    *Changes\ not\ staged* ) state="#[bg=brightred,fg=black] ± #[fg=default]#[bg=brightcyan, fg=brightred]$SEP" ;;
    *Changes\ to\ be\ committed* ) state="#[bg=blue,fg=black] + #[default]#[bg=bightcyan, fg=blue]$SEP" ;;
    * ) state="#[bg=green,fg=black] ✔ #[default]#[bg=brightcyan, fg=green]$SEP" ;;
  esac
  if [[ $git_branch = "master" ]]; then
    git_base_name=$(cd $1 && git rev-parse --show-toplevel)
    git_info="$state#[bg=brightcyan,fg=black] ${git_branch} #[bg=brightblue, fg=brightcyan]$SEP"
    directory="#[bg=brightblue,fg=black] $git_base_name#[bg=default, fg=brightblue]$SEP"
  else
    git_base_name=$(cd $1 && git rev-parse --show-toplevel)
    git_info="$state#[bg=brightcyan,fg=black] ${git_branch} #[bg=brightblue, fg=brightcyan]$SEP"
    directory="#[bg=brightblue,fg=black] $git_base_name#[bg=default, fg=brightblue]$SEP"
  fi
else
  directory="#[bg=brightblue,fg=black] $1#[bg=default, fg=brightblue]$SEP"
  git_info=""
fi

echo "$git_info$directory"
