#!/bin/zsh

SEP=`echo ""`
if git_status=$(cd $1 && git status 2>/dev/null ); then
  git_branch="$(echo $git_status| awk 'NR==1 {print $3}')"
  case $git_status in
    *Changes\ not\ staged* ) state="#[bg=colour013, fg=brightcyan]$SEP#[bg=colour013,fg=black] ± #[fg=default]#[bg=default, fg=colour013]$SEP" ;;
    *Changes\ to\ be\ committed* ) state="#[bg=blue, fg=brightcyan]$SEP#[bg=blue,fg=black] + #[default]#[bg=default, fg=blue]$SEP" ;;
    * ) state="#[bg=green, fg=brightcyan]$SEP#[bg=green,fg=black] ✔ #[default]#[bg=default, fg=green]$SEP" ;;
  esac
  if [[ $git_branch = "master" ]]; then
    git_base_name=$(cd $1 && git rev-parse --show-toplevel)
    git_info="#[bg=brightcyan,fg=black] ${git_branch}$state"
    directory="#[bg=brightblue,fg=black] $git_base_name#[bg=brightcyan, fg=brightblue]$SEP"
  else
    git_base_name=$(cd $1 && git rev-parse --show-toplevel)
    git_info="#[bg=brightcyan,fg=black] ${git_branch}$state"
    directory="#[bg=brightblue,fg=black] $git_base_name#[bg=brightcyan, fg=brightblue]$SEP"
  fi
else
  directory="#[bg=brightblue,fg=black] $1#[bg=default, fg=brightblue]$SEP"
  git_info=""
fi

echo "$directory$git_info"
