[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
  let g:jedi#use_tabs_not_buffers = 1 
  let g:jedi#popup_select_first = 0 
  let g:jedi#popup_on_dot = 0 
  let g:jedi#goto_command = "<leader>d"
  let g:jedi#goto_assignments_command = "<leader>g"
  let g:jedi#goto_definitions_command = ""
  let g:jedi#documentation_command = "K"
  let g:jedi#usages_command = "<leader>n"
  let g:jedi#rename_command = "<leader>R" 
  let g:jedi#completions_command = "<S-TAB>"
	autocmd FileType python setlocal completeopt-=preview
'''


[[plugins]]
repo = 'zchee/deoplete-clang'
hook_source = '''
let g:deoplete#sources#clang#libclang_path = '/usr/local/Cellar/llvm/7.0.0/lib/libclang.dylib'
let g:deoplete#sources#clang#clang_header = '/usr/local/Cellar/llvm/7.0.0/lib/clang'
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = '''
    let g:deoplete#sources#jedi#python_path = '/Users/.pyenv/shims/python3'
'''
on_ft = ['c', 'cpp', 'cmake']
depends = ['deoplete.nvim']



[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'justmao945/vim-clang'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'


[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'



















