[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'psf/black'

[[plugins]]
repo = 'heavenshell/vim-pydocstring'
build = 'make install'
on_ft = ['python']
hook_add = '''
    let g:pydocstring_formatter = 'google'
    nmap <leader>pd <Plug>(pydocstring)
'''

[[plugins]]
repo = 'rhysd/conflict-marker.vim'
hook_add = '''
    nmap <leader>ct :<C-u>ConflictMarkerThemselves<CR>
    nmap <leader>co :<C-u>ConflictMarkerOurselves<CR>
    nmap <leader>cb :<C-u>ConflictMarkerBoth<CR>
'''

[[plugins]]
repo = 'linty-org/key-menu.nvim'
