
# [[plugins]]
# repo = 'nvim-treesitter/nvim-treesitter'
# # https://discourse.nixos.org/t/cant-get-nvim-treesitter-neovim-plugin-to-work-properly/21368
# rev = "501db1459a7a46cb0766b3c56e9a6904bbcbcc97"
# on_event = 'VimEnter'
# hook_source = '''
# " nvim-treesitter
# if !exists('g:vscode')
# lua <<EOF
# require'nvim-treesitter.configs'.setup {
#   highlight = {
#     enable = true,
#   },
#   ensure_installed = {"go", "python", "lua", "yaml", "json",  "bash", "latex", "fish", "gomod", "html", "toml", "vim", "ruby", "c", "cpp", "c_sharp", "comment", "jsonc", "javascript", "cuda", "scala", "dockerfile", "rust", "query", "julia", "lua"},
#   indent = {
#     enable = true,
#   },
#   textobjects = {
#     select = {
#       enable = true,
# 
#       -- Automatically jump forward to textobj, similar to targets.vim
#       lookahead = true,
# 
#       keymaps = {
#         -- You can use the capture groups defined in textobjects.scm
#         ["af"] = "@function.outer",
#         ["if"] = "@function.inner",
#         ["ac"] = "@class.outer",
#         ["ic"] = "@class.inner",
#       },
#     },
#   },
# }
# EOF
# endif
# '''


# resize window
# [[plugins]]
# repo = 'simeji/winresizer'
# on_event = 'VimEnter'
# hook_add = '''
#     let g:winresizer_start_key = '<C-w>'
#     let g:winresizer_vert_resize = 1
#     let g:winresizer_horiz_resize = 1
# '''

# fuzzy finder
# 使ってるかわからない
# [[plugins]]
# repo = 'junegunn/fzf'
# on_event = 'VimEnter'
# build = './install --all'
# [[plugins]]
# repo = 'junegunn/fzf.vim'
# on_event = 'VimEnter'
