[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'justmao945/vim-clang'

[[plugins]]
repo = 'psf/black'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'yuezk/vim-js'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'haya14busa/is.vim'
on_event = 'VimEnter'

[[plugins]]
repo = 'haya14busa/vim-asterisk'
depends = ['is.vim']
on_map = ['<Plug>(asterisk-']
hook_post_source  = 'let g:asterisk#keeppos = 1'

[[plugins]]
repo = 'heavenshell/vim-pydocstring'
build = 'make install'
on_ft = ['python']
hook_add = '''
    let g:pydocstring_formatter = 'google'
    nmap <leader>pd <Plug>(pydocstring)
'''

[[plugins]]
repo = 'rhysd/conflict-marker.vim'
hook_add = '''
    nmap <leader>ct :<C-u>ConflictMarkerThemselves<CR>
    nmap <leader>co :<C-u>ConflictMarkerOurselves<CR>
    nmap <leader>cb :<C-u>ConflictMarkerBoth<CR>
'''

[[plugins]]
repo = 'linty-org/key-menu.nvim'
