[[plugins]]
repo = 'dbgx/lldb.nvim'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'nvim-lua/popup.nvim'
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# ecosystem plugin using deno
[[plugins]]
repo = "vim-denops/denops.vim"

[[plugins]]
repo = 'camspiers/snap'

[[plugins]]
repo = 'ibhagwan/fzf-lua'
[[plugins]]
repo = 'vijaymarupudi/nvim-fzf'



# language server manager
# [[plugins]]
# repo = 'neoclide/coc.nvim'
# build = './install.sh nightly'
# hook_add = '''
#     let coc#util#get_data_home = '~/.config/coc'
# '''




