[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-scripts/wombat256.vim'


[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ],
      \             [ 'vista' ],
      \           ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'fugitive#head',
      \   'vista': 'NearestMethodOrFunction',
      \ },
      \ }
function! NearestMethodOrFunction() abort
  return get(b:, 'vista_nearest_method_or_function', '')
endfunction
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'

[[plugins]]
repo='zxqfl/tabnine-vim'

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'
